### ISSUE TITLE
El repo necesita mas contenido

### ISSUE THREAD

**Issue by yabellini** [bdirienzo/goatR#1]
Hola, muy bien que generaron el repositorio y el proyecto, pero esta muy vacio.

Por favor publiquen los avances que tengan de las funciones, documentacion, etc.  del paquete. Recuerden es parte del segundo examen parcial.

Podemos dar feedback antes si esta publicado aqui.

**Comment by bdirienzo** [comment]
Hola profe!
Les queríamos preguntar sobre ese tema en la clase, porque varios grupos tenemos la misma duda.
No terminamos de entender bien qué funciones hay que incluir dentro del paquete. No sabemos si tenemos que inventar algunas o utilizar algunas viejas. Es por eso que no pudimos avanzar mucho y por lo que el README y los archivos están vacíos.

Gracias

Bernardo Di Rienzo<https://aka.ms/o0ukef>
________________________________
De: Yanina Bellini Saibene ***@***.***>
Enviado: Tuesday, October 15, 2024 10:38:59 PM
Para: bdirienzo/goatR ***@***.***>
Cc: Subscribed ***@***.***>
Asunto: [bdirienzo/goatR] El repo necesita mas contenido (Issue #1)


ATENCIÓN: Este correo electrónico proviene de un remitente EXTERNO a la organización. Solo abrí archivos adjuntos o ingresá a sus links si reconocés al remitente y confías en su contenido.

________________________________

Hola, muy bien que generaron el repositorio y el proyecto, pero esta muy vacio.

Por favor publiquen los avances que tengan de las funciones, documentacion, etc. del paquete. Recuerden es parte del segundo examen parcial.

Podemos dar feedback antes si esta publicado aqui.

**Comment by bdirienzo** [comment]
Genial profe, hay algunos que ya los tenemos hechos de la práctica para el parcial así que reutilizamos eso y agregamos si falta.

Muchas gracias!
