### ISSUE TITLE
Codecov

### ISSUE THREAD

**Issue by bdirienzo** [bdirienzo/goatR#17]
Hola @yabellini! Estamos teniendo problemas con la conexión remota a codecov. Si realizo el codecov por consola me sale perfecto, pero no se conecta a la página. La primera vez lo hizo, pero luego no sé actualizó más. 

Gracias
Saludos

**Comment by bdirienzo** [comment]
Ah listo. Nosotros cargamos un token que nos en settings como secret. Pero sin embargo sigue fallando. 

Gracias

**Comment by yabellini** [comment]
Es bueno saber que intentaron lo del token.  Voy a intentar verlo en algun momento y vuelvo a ustedes si encuentro cual es el problema.

**Comment by bdirienzo** [comment]
Dale, gracias
