### ISSUE TITLE
Netlify y theme

### ISSUE THREAD

**Issue by bdirienzo** [bdirienzo/goatR#20]
Hola @yabellini! Conectamos nuestra web a goatr.netlify.app, como tienen ustedes el apunte. Porque estamos tratando de hacer el paquete lo más completo posible con lo que sabemos y también sumándole cosas que todavía no aprendimos con el ChatGPT.
Tenemos un problema con el theme de la web. Vi que ustedes subieron en el apunte la página de pkgdown con la documentación para personalizar la web. Revisamos y encontramos un theme que nos gusta (morph) sin embargo no estamos pudiendo cambiarlo en nuestro paquete. No sabemos bien qué archivo modificar y en qué ubicación guardar el css descargado, porque cuando parecería que está todo bien y hacemos el build_site se borra todo. 

Gracias

**Comment by yabellini** [comment]
Hola, miraron esta pagina para ver como personalizar su sitio?  
Esta es la documentacion oficial https://pkgdown.r-lib.org/articles/customise.html

**Comment by yabellini** [comment]
Si entiendo bien, ustedes logran cambiar el aspecto de la pagina y localmente se construye de forma correcta, luego cuando lo publican en Netlify no se actualiza correctamente?

Como configuraron Netlify?

**Comment by yabellini** [comment]
Igual como aclaracion Netlify o GitHub pages es lo mismo.  Son dos plataformas para el mismo servicio de tener paginas web estaticas publicadas.

**Comment by bdirienzo** [comment]
Ahh no sabíamos de Git Pages. Porque nuestra página había quedado tipo html local y pensamos que era la única forma. Así que lo conectamos con Netifly. 

Netifly yo creo que es lo único que funciona 100% bien en nuestro repo JAJAJA. Está configurado para que cada vez que se realiza un push se haga un deploy en la web. El tema está en cambiar el diseño de la página. El visual editor de Netifly no lo podemos activar, entiendo por lo que averigüé que por un tema del tipo de página. Así que no nos queda otra más que hacerlo por código, ahí es donde aparecen nuestros problemas. Porque por más que intentemos no podemos modificar el css con el del theme de pkgdown, que sacamos de la documentación. 

Cuando reemplazamos el css que descargamos en la carpeta /docs, modificamos el yaml y hacemos un pkgdown::build_site todo vuelve a como estaba antes.

**Comment by yabellini** [comment]
Esta es la documentacion the pkgdown para hacer cambios esteticos a un sitio construido con el paquete: [pkgdown.r-lib.org/articles/customise.html](https://pkgdown.r-lib.org/articles/customise.html)

Cambiar se puede, por ejemplo todos nuestros paquetes tienen el mismo tema con el branding de la organizacion: https://docs.ropensci.org/allcontributors/

**Comment by yabellini** [comment]
Y si la carpeta doc se regenera cada vez que se hace un build asi que tiene sentido que todo lo que no sea lo standar se borre, como el css de ustedes.  

Aca hay un ejemplo del pkgdown.yml con configuraciones personalizadas: https://github.com/ropensci/karel/blob/master/_pkgdown.yml

Aqui hay otro ejemplo donde usan una carpeta que se llama pkgdown con la info del tema del paquete: https://github.com/ropensci/eph/tree/master/pkgdown
Esta se ve asi: https://ropensci.github.io/eph/

**Comment by bdirienzo** [comment]
Genial, gracias! Probamos y te aviso

**Comment by bdirienzo** [comment]
Hola profe, no hubo caso. Seguimos sin poder cambiar la página en si.Cualquier modificación manual que hagamos dentro del /docs no tiene ningún efecto en la web.

Gracias
