### ISSUE TITLE
Download y load

### ISSUE THREAD

**Issue by bdirienzo** [bdirienzo/goatR#4]

**Comment by bdirienzo** [comment]
Problemas con el load para cargar el dataset al environment

**Comment by paocorrales** [comment]
Les dejo un comentario sobre el problema que mencionaron en el documento de trabajo. 

Los matadatos y los datos son por naturaleza muy distintos por lo que es recomendable acceder a cada uno con funciones distintas. Para unirlos (si es eso lo que quieren hacer) pueden usar alguna de las funciones joins.

**Comment by paocorrales** [comment]
Otro detalle, revisé la función download_datasets()` y no ajusta del todo a la consigna. 
* En primer lugar si es una función exportada, es decir, para que el usuario pueda usarla, nunca vamos a agregar funciones de usethis porque correrian cada vez que se ejecuta la función y esto no tiene sentido. La función `usethis::use_data()` se usa solo del lado del desarrollador. 
* La función debería recibir como argumento de entrada el id de la estación y la ruta al archivo donde se quieren guardar los datos y devolver un dataframe con los datos que se descargaron y leyeron. Si prefieren separar esto en 2 funciones, una para la descarga y otra para la lectura, entonces la de descarga puede devolver la ruta al archivo que se descargó y la función de lectura puede recibir eso como argumento y devolver un dataframe.
* Los datos a incluir en el paquete pueden ser solo una muestra de todos los datos disponibles, tal vez 1 o 2 estaciones o solo algunos años de datos para pocas estaciones. Pero separen esto de las funciones de lectura y descarga.

**Comment by bdirienzo** [comment]
Buenas días @paocorrales, perfecto, hicimos como nos dijiste. Creamos dos funciones separadas. 

Una de ellas download_packages () la cual puede recibir dos argumentos, aunque no es necesario. Uno argumento es el id de la estación y el otro el path. Si no pones el id de estación te guarda todos los archivos. Si no pones el path te los guarda en una carpeta por defecto. Todo esto, está igualmente explicado en la documentación. 

La otra función es read_packages(), la cual recibe dos argumentos, id de la estación y el path. Es necesario si o si uno de los dos para que funcione. Si pones unicamente el id de la estación, la función va a intentar buscar el dataset en la carpeta por defecto. Si pones el path, lo va a buscar donde le indiques. Y la otra posibilidad es guardar en una variable el return de la función download_packages y entregarlo como argumento de path a la función read. Todo esto también esta documentado.

Después si nos podes decir si está bien sería genial.
Muchísimas gracias

**Comment by bdirienzo** [comment]
Hola Pao, te puedo hacer otra consulta con respecto a la función download_datasets? Empezamos el testeo, y no estamos seguros con los que nosotros llamamos test 7. Porque para testear si el archivo se guarda en una ubicación distinta a la predeterminada tenemos que utilizar un path propio, lo que hace que el testeo no se pueda replicar en otros ordenadores.

Gracias

**Comment by paocorrales** [comment]
Chicos no puedo ver los tests (creo que aun no los subieron a este repo) pero la solución para el tipo de problema que tienen es usar `tempdir()` y o `tempfile()`. Crean ubicaciones temporales que leugo se borran y funciona para cualquier computadora.

**Comment by lautarosanfi** [comment]
Hola Pao, genial, ya pudimos resolverlo.

Gracias
